// THE QUOTES, AND EVERY CONTAINER THEY SIT IN — the director's cut only.
//
// One quote per element, shown three ways: on the full-screen discovery card,
// under the result in the cauldron, and on the element's row in the codex.
// Nothing here reaches a shipping build. Each of the three call sites in
// game.ts is a `__DIRECTOR__ ? ... : ""`, and __DIRECTOR__ is a literal by the
// time closure runs, so ADVANCED folds every one of them to an empty string,
// then finds these four exports unreferenced and deletes them — the table, the
// markup and the rules that style it. That is the whole reason the quotes live
// in their own module rather than as a `q` field on ElementDef: a field on a
// live object is reachable, and 101 strings that closure cannot prove dead are
// 101 strings roadroller has to model.
//
// So this file is written for READING, not for packing. It is the one place in
// the game where a byte costs nothing.

// id -> quote. Ids are elements.ts's own; a missing one renders as "undefined"
// rather than throwing, which is the right failure for a cut nobody ships.
export const QUOTE: Record<string, string> = {
  red: "All hands to battle stations!",
  green: "In every wood, in every spring, there is a different green.",
  blue: "The closest color to truth.",
  yellow: "Pikachu, I choose you!",
  magenta: "The fire that red attempts to be, and purple secretly desires.",
  cyan: "Cyan is sus",
  turquoise: "A man may prefer navy to turquoise, but it's a distinction of confidence.",
  chartreuse: "The only liqueur so good they named a color after it.",
  crimson: "It is courage, courage, courage, that raises the blood of life to crimson splendor.",
  teal: "The ocean keeps its deepest secrets in shades of teal.",
  beige: "The color of indecision.",
  white: "Let there be light.",
  orange: "The new black.",
  violet: "The last color of the rainbow.",
  indigo: "Here because Newton insisted.",
  pink: "You can never go wrong with a little pink, a lot works too.",
  brown: "The very shade of earth itself.",
  matter: "Energy waiting to happen.",
  air: "The air is full of ideas. They are knocking you in the head all the time.",
  sky: "Only from the heart can you touch the sky.",
  gold: "Gold can do much, but love can do all.",
  copper: "Through love, scraps of copper are turned to gold.",
  silver: "Pure silver fears no stain.",
  water: "Be like water, my friend.",
  fire: "Fire transforms all things it touches.",
  earth: "Keep your feet on the ground and keep reaching for the stars.",
  clay: "Shape clay into a vessel; it is the space within that makes it useful.",
  pottery: "Who is the Potter, pray, and who the Pot?",
  brick: "Even a brick wants to be something.",
  house: "May your house always be too small for all your friends.",
  window: "A room without a view is a body without a soul.",
  hospital: "A house of hope.",
  hut: "Better a hut where one laughs than a palace where one weeps.",
  bank: "The best way to rob a bank is to own one.",
  beer: "Beer is proof that God loves us and wants us to be happy.",
  wine: "Wine is sunlight, held together by water.",
  blood: "Thicker than water.",
  coffee: "The favorite drink of the civilized world.",
  lava: "The floor is lava!",
  volcano: "A cannon of immense size.",
  mountain: "It is not the mountain we conquer, but ourselves.",
  goat: "Greatest of all time!",
  stone: "Every stone holds a statue; the sculptor merely reveals it.",
  troll: "Don't feed the trolls.",
  metal: "Soft enough to wire, hard enough to shield, liquid enough to pour.",
  anchor: "Hope is the anchor of the soul.",
  rust: "It's better to burn out than to rust out.",
  tool: "We shape our tools, and thereafter our tools shape us.",
  pick: "During a gold rush, sell pickaxes.",
  scale: "The scales of justice don't always balance nicely... real life is about wounds and scars.",
  shovel: "To plant a pine, one need be neither god nor poet; one need only own a shovel.",
  sand: "It's coarse and rough and irritating and it gets everywhere.",
  glass: "Glass, china, and reputation are easily cracked, and never well mended.",
  mirror: "Who's the Fairest of Them All?",
  hourglass: "Like sands through the hourglass, so are the days of our lives.",
  sun: "Even the darkest night will end and the sun will rise.",
  night: "A world lit by itself.",
  star: "The forget-me-nots of the angels.",
  moon: "Everyone is a moon, and has a dark side which he never shows to anybody.",
  telescope: "I have seen what no human eyes have seen before.",
  comet: "Comets are like cats: they have tails, and they do precisely what they want.",
  ghost: "I ain't afraid of no ghost.",
  cloud: "Resembles the thoughts in our mind! Both change from second to second!",
  rain: "If you want the rainbow, you have to put up with the rain.",
  lightning: "Never strikes twice.",
  storm: "It was the most terrible, yet majestic spectacle.",
  umbrella: "The human mind is like an umbrella; it functions best when open.",
  parachute: "If at first you don't succeed, skydiving is definitely not for you.",
  tornado: "I've a feeling we're not in Kansas anymore.",
  fog: "The fog hides the world, but it reveals the mystery.",
  life: "It finds a way.",
  alien: "If it's just us, it seems like an awful waste of space.",
  uFO: "Not constructed by any power on Earth.",
  jellyfish: "Go with the flow.",
  coral: "Individual coral polyps are tiny, but together they build structures visible from space.",
  egg: "Which came first?",
  cooking: "A recipe has no soul. You, as the cook, must bring soul to the recipe.",
  animal: "All animals are equal, but some are more equal than others.",
  rat: "The trouble with the rat race is that even if you win, you're still a rat.",
  lizard: "Life's better on a warm rock.",
  turtle: "Slow and steady wins the race.",
  snake: "When you see a snake, never mind where he came from.",
  dodo: "The Dodo never had a chance. He seems to have been invented for the sole purpose of becoming extinct.",
  dinosaur: "Dinosaurs are nature's special effects.",
  sauropod: "Designed to convert immense amounts of foliage into sheer mass.",
  frog: "It's not easy being green.",
  camel: "Trust in God, but tie your camel.",
  crab: "You can never teach a crab to walk straight.",
  lobster: "An expensive, edible vehicle for melted butter.",
  scorpion: "Will bite even the hand that saves it.",
  horse: "My kingdom for a horse!",
  sheep: "It is better to live one day as a lion than a hundred years as a sheep.",
  yarn: "The web of our life is of a mingled yarn, good and ill together.",
  spider: "What is normal for the spider is chaos for the fly.",
  web: "What a tangled web we weave, when first we practise to deceive!",
  scarf: "A great way to dress up a plain outfit!",
  "teddy bear": "Bears need people. People need bears.",
  hippo: "The world's most dangerous couch potato.",
  wolf: "If you live with wolves, you must learn to howl.",
  fox: "The fox changes his skin, but not his habits.",
  bone: "Flesh decays; bone endures.",
  dog: "The more I learn about people, the more I like my dog.",
  cow: "One end is moo, the other, milk.",
  milk: "Got milk?",
  cat: "Time spent with cats is never wasted.",
  "black cat": "All cats are black in the dark.",
  custard: "There is no issue so complex that it cannot be simplified by a bowl of warm custard.",
  cheese: "The nectar of the Gods.",
  squirrel: "You can't keep a squirrel on the ground.",
  monkey: "Even a monkey can fall from a tree.",
  orangutan: "Orangutans look straight into your soul.",
  human: "To err is human; to forgive, divine.",
  chef: "This lamb is so raw, it's still singing Mary Had a Little Lamb!",
  knife: "A sharp knife is a safe knife.",
  burger: "The cornerstone of any nutritious breakfast.",
  sushi: "The fine art of preparing sushi is something that you watch and learn.",
  "french fries": "Show me a person who doesn't like french fries and we'll swap lies.",
  pizza: "When it's good, it's really good; when it's bad, it's still pretty good.",
  fondue: "One pot, shared warmth, and endless dipping.",
  party: "Life is a party. Dress like it.",
  dancing: "Dance first. Think later. It's the natural order.",
  fireworks: "Rising, shining, scattering, and finally fading.",
  champagne: "In victory one deserves it; in defeat one needs it.",
  "ice cream": "Tomorrow we can eat broccoli, but today is for ice cream.",
  salad: "A salad is not a meal, it is a style.",
  ratatouille: "Not anyone can become a great artist, but a great artist can come from anywhere.",
  eyeglasses: "Words are like eyeglasses; they blur everything that they do not make clear.",
  sunglasses: "The ultimate accessory.",
  goggles: "If you think safety is expensive, try an accident.",
  "diving mask": "To observe a fish, become a fish.",
  shoe: "It's not the mountain ahead to climb that wears you out; it's the pebble in your shoe.",
  boot: "My optimism wears heavy boots and is loud.",
  socks: "One can never have enough socks.",
  climbing: "The best climber is the one having the most fun.",
  ladder: "You cannot climb the ladder of success with your hands in your pockets.",
  racing: "You can't win a race in the first turn, but you can certainly lose it.",
  skiing: "If you're not falling, you're not learning.",
  "ice skate": "If skating teaches you anything, it's how to fall spectacularly.",
  ninja: "Only a ninja can stop a ninja.",
  wizard: "Do not meddle in the affairs of wizards, for they are subtle and quick to anger.",
  vampire: "Evil is a point of view.",
  statue: "I saw the angel in the marble and carved until I set him free.",
  farmer: "Cultivators of the earth are the most valuable citizens.",
  firefighter: "The only job where you can smash someone's window with an axe and get a thank-you note for it.",
  extinguisher: "Pull, Aim, Squeeze, Sweep.",
  artist: "Inspiration exists, but it has to find you working.",
  brush: "Words are your paintbrush, and your life is the canvas.",
  painting: "I found I could say things with color and shapes that I couldn't say any other way.",
  clown: "Clowns are the pegs on which the circus is hung.",
  circus: "The circus arrives without warning.",
  elephant: "They say an elephant never forgets. What they don't tell you is, you never forget an elephant.",
  mammoth: "The iconic symbol of a lost world.",
  mermaid: "We got no troubles, life is the bubbles, under the sea!",
  snowman: "Hi, everyone! I'm Olaf and I like warm hugs.",
  swimming: "If you want to learn to swim, jump into the water.",
  santa: "Santa Claus is anyone who loves another and seeks to make them happy.",
  christmas: "Christmas isn't a season. It's a feeling.",
  gift: "The manner of giving is worth more than the gift.",
  robot: "These aren't the droids you're looking for.",
  astronaut: "That's one small step for man, one giant leap for mankind.",
  zombie: "When there's no more room in hell, the dead will walk the earth.",
  skull: "That skull had a tongue in it, and could sing once.",
  coffin: "The only way you can become a legend is in your coffin.",
  headstone: "Reading epitaphs, we find that most tombstones are larger than the lives they cover.",
  "x-ray": "In X-ray photos, structure becomes transparency and transparency manifests structure.",
  teacher: "Those who know, do. Those that understand, teach.",
  school: "An investment in knowledge pays the best interest.",
  student: "Always walk through life as if you have something new to learn, and you will.",
  scientist: "The one who asks the right questions.",
  doctor: "A good doctor treats the disease; the great doctor treats the patient who has the disease.",
  judge: "A judge is a student who marks his own examination papers.",
  syringe: "A needle can save a life or destroy one, depending entirely on whose hand holds the syringe.",
  bird: "To have faith is to have wings.",
  nest: "A bird is safe in its nest, but that is not what its wings are made for.",
  chick: "Are you my mother?",
  penguin: "Always dressed to impress and ready for any occasion.",
  duck: "If it looks like a duck and quacks like a duck, it's a duck.",
  fish: "So long, and thanks for all the fish.",
  sea: "The voice of the sea speaks to the soul.",
  boat: "A smooth sea never made a skilled sailor.",
  octopus: "The closest we will ever come to meeting an intelligent alien.",
  salt: "The only rock we eat.",
  shark: "You're gonna need a bigger boat.",
  owl: "Spanish or Vanish",
  bat: "Twinkle, twinkle, little bat! How I wonder what you're at!",
  flamingo: "Be a flamingo in a flock of pigeons.",
  pig: "Never wrestle with a pig. You both get dirty and the pig likes it.",
  boar: "A mountain boar cannot appreciate fine grain.",
  bacon: "Even the frying of bacon sounds like applause.",
  sandwich: "The one thing I can cook.",
  swan: "The ugly duckling was a swan all along.",
  peacock: "I'm a peacock, you gotta let me fly!",
  eagle: "Great eagles fly alone, and are not sucked up in the storm of factions.",
  peace: "May the dove of peace fly over every land, so that hatred and violence may yield to love and reconciliation.",
  phoenix: "From the ashes, a fire shall be woken",
  crow: "If men had wings and bore black feathers, few of them would be clever enough to be crows.",
  worm: "The early bird catches the worm.",
  bug: "The little things that run the world.",
  ant: "Ants are individual cells of a single superorganism.",
  fly: "A fly can trouble a lion more than a lion can trouble a fly.",
  cricket: "To live happily, live hidden.",
  ladybug: "So delightfully hemispherical.",
  roach: "There is seldom just one cockroach in the kitchen.",
  bee: "Busy bees make more honey.",
  mosquito: "If you think you are too small to make a difference, try sleeping with a mosquito.",
  butterfly: "Float like a butterfly, sting like a bee.",
  fairy: "Some day you will be old enough to start reading fairy tales again.",
  honey: "Life is the flower for which love is the honey.",
  bear: "Sometimes you eat the bear, and sometimes the bear eats you.",
  "polar bear": "The undisputed king of the ice.",
  acid: "Water that bites.",
  electricity: "So subtle and powerful that it seems to be the very soul of the universe.",
  "light bulb": "I have not failed. I've just found 10,000 ways that won't work.",
  plug: "Almost everything will work again if you unplug it for a few minutes, including you.",
  magnet: "The force of magnetism is one of the most subtle and mysterious in nature.",
  ice: "Let it go!",
  snow: "Winter is coming.",
  prism: "Every eye is a different prism, showing a different world.",
  rainbow: "Somewhere over the rainbow, skies are blue.",
  magic: "Any sufficiently advanced technology is indistinguishable from magic.",
  "crystal ball": "Reply hazy, try again.",
  unicorn: "Always be yourself. Unless you can be a unicorn, then always be a unicorn.",
  plant: "Grow where you are planted.",
  medicine: "To cure sometimes, to relieve often, to comfort always.",
  potato: "Boil 'em, mash 'em, stick 'em in a stew.",
  carrot: "Carrots are a great thing to eat when you're hungry and want to stay that way.",
  eggplant: "Very well, I will marry you if you promise not to make me eat eggplant.",
  corn: "An efficient way to get energy calories off the land.",
  popcorn: "Love is sharing your popcorn.",
  rabbit: "What's up, doc?",
  cactus: "Adapt to your environment, grow thick skin, and stay sharp.",
  desert: "A natural extension of the silent mind.",
  field: "Pray for a good harvest, but keep on plowing.",
  wheat: "For wheat is wheat, even if people think it is a grass in the beginning.",
  bread: "Good bread is the most fundamentally satisfying of all foods.",
  "hot dog": "A hot dog is a sandwich, but only if you want to start a heated argument.",
  croissant: "Croissants in Paris are warm and soft, golden and buttery, like baked clouds.",
  waffle: "You can't be sad if you're eating a waffle!",
  pie: "Cut my pie into four pieces, I don't think I could eat eight.",
  pretzel: "These pretzels are making me thirsty!",
  rice: "Rice is born in water and dies in wine.",
  "white rice": "At home, a bowl of long-grain white rice will get a stream of melted butter and a crumbling of sea salt.",
  paella: "A dish that brings people together.",
  curry: "Without the curry, boiled rice can be very dull.",
  sake: "The best of all medicines.",
  park: "Not an island of nature, but a bridge connecting humans back to it.",
  playground: "The world is a playground, and you know that when you're a kid, but somewhere along the way everyone forgets it.",
  tree: "He who plants a tree, plants a hope.",
  palm: "The palm tree that sways in the breeze stays standing the longest.",
  island: "A prison for some and a refuge for others.",
  world: "The world is full of magical things, patiently waiting for our senses to grow sharper.",
  map: "It is not down in any map; true places never are.",
  compass: "Living without an aim is like sailing without a compass.",
  fruit: "An apple a day keeps the doctor away.",
  juice: "The darker the berry, the sweeter the juice.",
  banana: "Time flies like an arrow; fruit flies like a banana.",
  blueberries: "If love were a fruit, it would be a blueberry: small, sweet, and bursting with life.",
  grapes: "The sun, with all those planets revolving around it, can still ripen a bunch of grapes as if it had nothing else in the universe to do.",
  lime: "A lime is just a lemon that never lost its cool.",
  lemon: "When life gives you lemons, make lemonade.",
  tangerine: "Love like rain, like the smell of a tangerine, like a surprise found in your pocket.",
  olive: "An olive orchard is a gold mine that never runs dry.",
  gorilla: "If you're going to act like a gorilla, you might as well look like one.",
  coconut: "Tough on the outside, sweet on the inside.",
  pumpkin: "Trick or treat!",
  axe: "No axe can cut wood without a handle made from the forest.",
  wood: "Chop your own wood and it will warm you twice.",
  saw: "Measure twice, cut once.",
  bamboo: "Even the tallest bamboo began as a tiny sprout beneath the soil.",
  panda: "When you see them, they're just sitting in the jungle eating.",
  beaver: "Nature's ultimate ecosystem engineers.",
  charcoal: "Charcoal never forgets that it was once wood.",
  ash: "Ashes to ashes, dust to dust.",
  mushroom: "All are edible, but some only once.",
  pencil: "A pencil and a dream can take you anywhere.",
  paper: "Paper has more patience than people.",
  book: "A room without books is like a body without a soul.",
  palette: "I dream of painting and then I paint my dream.",
  kite: "Kites rise highest against the wind, not with it.",
  scissors: "The thing with high-tech is that you always end up using scissors.",
  poodle: "I wonder if other dogs think poodles are members of a weird religious cult.",
  bookmark: "History left behind is like a bookmark in a classic.",
  iD: "Be yourself; everyone else is already taken.",
  black: "Only in the darkness can you see the stars.",
  diamond: "Life tries to crush you, but you choose whether to become dust or a diamond.",
  ring: "One ring to bring them all, and in the darkness bind them.",
  crown: "Uneasy lies the head that wears a crown.",
  king: "Hail to the king, baby.",
  castle: "Castles in the air are the only ones that cost nothing to keep up.",
  lion: "Remember who you are. You are my son, and the one true king.",
  tiger: "The tiger will tear you apart, but it won't judge you.",
  wedding: "The best thing to hold onto in life is each other.",
  baby: "People who say they sleep like a baby usually don't have one.",
  angel: "Angels fly because they take themselves lightly.",
  blossom: "Where flowers bloom so does hope.",
  "cherry blossom": "Under the cherry blossoms, none are strangers.",
  nut: "God gives the nuts, but he does not crack them.",
  peanut: "If you pay peanuts, you get monkeys.",
  sunflower: "Wherever the sun goes, the sunflower will follow.",
  rose: "A rose by any other name would smell as sweet.",
};

// The discovery card: an italic line under the new element's name.
export const cardQuote = (id: string): string =>
  "<i>\u201C" + QUOTE[id] + "\u201D</i>";

// The cauldron well, appended to the name already sitting there.
export const wellQuote = (id: string): string =>
  " \u2014 \u201C" + QUOTE[id] + "\u201D";

// The codex row, under the name and the recipes that made it.
export const codexQuote = (id: string): string =>
  '<div class=Q>' + QUOTE[id] + "</div>";

// The rules for those three containers, appended to the sheet by css.ts. They
// are here rather than in style.css for the same reason the strings are: a
// selector in the stylesheet ships whether or not anything wears the class,
// and in a shipping build nothing ever will. Not run through cssnano — it is
// concatenated onto the minified sheet at runtime — so it is written out plain.
export const QUOTE_CSS = `
#ds .c i { color: #8fb4d8; }
.Q { color: #55708e; font-size: 11px; font-style: italic; }
`;
